# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!

target 'TV Shows' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod "Alamofire"
  pod 'MBProgressHUD'
  # Pods for TV Shows
end
